# [Title]

## 1. Introduction

In [4]:
import numpy as np

# Single array
array = np.array([2, 5, 7])

# Matrix
matrix = np.array([[2, 7, 9], [0, -2, 5], [1, 1, 1]])

print(array)
print(matrix)

[2 5 7]
[[ 2  7  9]
 [ 0 -2  5]
 [ 1  1  1]]


### 1.1 Literature review of the compound (<500 words)

### 1.2 Literature review of the cell factory (<500 words)

## 2. Problem definition (<300 words)

## 3. *If Project category I:* Reconstruction of a new GSM for your cell factory host of interest (<1500 words)

or

## 3. *If Project category II:* Selection and assessment of existing GSM (<500 words)

## 4. Computer-Aided Cell Factory Engineering (<1500 words if Category II project; <500 words for Category I project)

## 5. Discussion (<500 words)

## 6. Conclusion (<200 words)

## References